/*****************************************
 * Filename: CC2500_regvalues.c
 * Author: AUTOGENERATED FILE DO NOT EDIT
 * Date: 11/19/2016
 * Description: Generated using TI SmartRF Studio
 */

#include "CC2500_regdefs.h"
#include <compiler.h>

uint8_t gCC2500RegDefaults[] = {
     [CC2500_IOCFG2] = 0x0B,
     [CC2500_IOCFG1] = 0x2E,
     [CC2500_IOCFG0] = 0x0C,
     [CC2500_FIFOTHR] = 0x07,
     [CC2500_SYNC1] = 0xD3,
     [CC2500_SYNC0] = 0x91,
     [CC2500_PKTLEN] = 0xFF,
     [CC2500_PKTCTRL1] = 0x04,
     [CC2500_PKTCTRL0] = 0x12,
     [CC2500_ADDR] = 0x00,
     [CC2500_CHANNR] = 0x00,
     [CC2500_FSCTRL1] = 0x08,
     [CC2500_FSCTRL0] = 0x00,
     [CC2500_FREQ2] = 0x5D,
     [CC2500_FREQ1] = 0x93,
     [CC2500_FREQ0] = 0xB1,
     [CC2500_MDMCFG4] = 0x86,
     [CC2500_MDMCFG3] = 0x83,
     [CC2500_MDMCFG2] = 0x00,
     [CC2500_MDMCFG1] = 0x22,
     [CC2500_MDMCFG0] = 0xF8,
     [CC2500_DEVIATN] = 0x44,
     [CC2500_MCSM2] = 0x07,
     [CC2500_MCSM1] = 0x30,
     [CC2500_MCSM0] = 0x18,
     [CC2500_FOCCFG] = 0x16,
     [CC2500_BSCFG] = 0x6C,
     [CC2500_AGCCTRL2] = 0x03,
     [CC2500_AGCCTRL1] = 0x40,
     [CC2500_AGCCTRL0] = 0x91,
     [CC2500_WOREVT1] = 0x87,
     [CC2500_WOREVT0] = 0x6B,
     [CC2500_WORCTRL] = 0xF8,
     [CC2500_FREND1] = 0x56,
     [CC2500_FREND0] = 0x10,
     [CC2500_FSCAL3] = 0xA9,
     [CC2500_FSCAL2] = 0x0A,
     [CC2500_FSCAL1] = 0x00,
     [CC2500_FSCAL0] = 0x11,
     [CC2500_RCCTRL1] = 0x41,
     [CC2500_RCCTRL0] = 0x00,
     [CC2500_FSTEST] = 0x59,
     [CC2500_PTEST] = 0x7F,
     [CC2500_AGCTEST] = 0x3F,
     [CC2500_TEST2] = 0x88,
     [CC2500_TEST1] = 0x31,
     [CC2500_TEST0] = 0x0B,
};