/* Address Config = No address check */
/* Base Frequency = 2433.000000 */
/* CRC Autoflush = false */
/* CRC Enable = false */
/* Carrier Frequency = 2433.000000 */
/* Channel Number = 0 */
/* Channel Spacing = 199.951172 */
/* Data Format = Synchronous serial mode */
/* Data Rate = 2.39897 */
/* Deviation = 38.085938 */
/* Device Address = 0 */
/* Manchester Enable = false */
/* Modulated = true */
/* Modulation Format = 2-FSK */
/* Packet Length = 255 */
/* Packet Length Mode = Infinite packet length mode */
/* Preamble Count = 4 */
/* RX Filter BW = 203.125000 */
/* Sync Word Qualifier Mode = No preamble/sync */
/* TX Power = 0 */
/* Whitening = false */

/* File containing definitions of CC2500 register addresses */
/* AUTOGENERATED FILE DO NOT EDIT */
/* Generation date: 11/19/2016 */
#include <compiler.h>

extern uint8_t gCC2500RegDefaults[];

#define CC2500_IOCFG2 (0x0000)
#define CC2500_IOCFG1 (0x0001)
#define CC2500_IOCFG0 (0x0002)
#define CC2500_FIFOTHR (0x0003)
#define CC2500_SYNC1 (0x0004)
#define CC2500_SYNC0 (0x0005)
#define CC2500_PKTLEN (0x0006)
#define CC2500_PKTCTRL1 (0x0007)
#define CC2500_PKTCTRL0 (0x0008)
#define CC2500_ADDR (0x0009)
#define CC2500_CHANNR (0x000A)
#define CC2500_FSCTRL1 (0x000B)
#define CC2500_FSCTRL0 (0x000C)
#define CC2500_FREQ2 (0x000D)
#define CC2500_FREQ1 (0x000E)
#define CC2500_FREQ0 (0x000F)
#define CC2500_MDMCFG4 (0x0010)
#define CC2500_MDMCFG3 (0x0011)
#define CC2500_MDMCFG2 (0x0012)
#define CC2500_MDMCFG1 (0x0013)
#define CC2500_MDMCFG0 (0x0014)
#define CC2500_DEVIATN (0x0015)
#define CC2500_MCSM2 (0x0016)
#define CC2500_MCSM1 (0x0017)
#define CC2500_MCSM0 (0x0018)
#define CC2500_FOCCFG (0x0019)
#define CC2500_BSCFG (0x001A)
#define CC2500_AGCCTRL2 (0x001B)
#define CC2500_AGCCTRL1 (0x001C)
#define CC2500_AGCCTRL0 (0x001D)
#define CC2500_WOREVT1 (0x001E)
#define CC2500_WOREVT0 (0x001F)
#define CC2500_WORCTRL (0x0020)
#define CC2500_FREND1 (0x0021)
#define CC2500_FREND0 (0x0022)
#define CC2500_FSCAL3 (0x0023)
#define CC2500_FSCAL2 (0x0024)
#define CC2500_FSCAL1 (0x0025)
#define CC2500_FSCAL0 (0x0026)
#define CC2500_RCCTRL1 (0x0027)
#define CC2500_RCCTRL0 (0x0028)
#define CC2500_FSTEST (0x0029)
#define CC2500_PTEST (0x002A)
#define CC2500_AGCTEST (0x002B)
#define CC2500_TEST2 (0x002C)
#define CC2500_TEST1 (0x002D)
#define CC2500_TEST0 (0x002E)
#define CC2500_PARTNUM (0x0030)
#define CC2500_VERSION (0x0031)
#define CC2500_FREQEST (0x0032)
#define CC2500_LQI (0x0033)
#define CC2500_RSSI (0x0034)
#define CC2500_MARCSTATE (0x0035)
#define CC2500_WORTIME1 (0x0036)
#define CC2500_WORTIME0 (0x0037)
#define CC2500_PKTSTATUS (0x0038)
#define CC2500_VCO_VC_DAC (0x0039)
#define CC2500_TXBYTES (0x003A)
#define CC2500_RXBYTES (0x003B)
#define CC2500_RCCTRL1_STATUS (0x003C)
#define CC2500_RCCTRL0_STATUS (0x003D)
